"""Initial migration

Revision ID: 5e8f64bb150b
Revises: 
Create Date: 2025-11-24 15:34:32.016527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8f64bb150b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('board',
    sa.Column('board_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('board_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('board_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('parent_comment', sa.BigInteger(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], ),
    sa.ForeignKeyConstraint(['parent_comment'], ['comment.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('like',
    sa.Column('like_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('board_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_table('comment')
    op.drop_table('board')
    op.drop_table('user')
    # ### end Alembic commands ###
